### PR TITLE
ft: social signup with facebook and google

### PR DESCRIPTION
**Pull request by Remkuzo98**
#### What does this PR do?

>It signs up the new user using social apps being either Facebook or google

#### How should this be manually tested?

- Clone this repo to your local repository 
-  git checkout to `ft-socialSignUp`
- `npm install`
- `npm run start` 
- use this route for signUp with google `localhost:5000/api/v1/users/signup/google`
- use this route for signUp with facebook `localhost:5000/api/v1/users/signup/facebook`

#### Screenshots (if appropriate)
N/A

### CODE REVIEW

**Review by bizip — CHANGES_REQUESTED** [review]
Hello and great job, I am trying to review test signup with google locally but I can't proceed with the first step.
guide me!
Screen Shot 2020-10-29 at 16 30 20

**Review by bizip — APPROVED** [review]

**Review by muhireheir — CHANGES_REQUESTED** [review]
fix the database related errors that are preventing the browser  to reload.

**Review by nishimweelysee — APPROVED** [review]
This PR is working correctly

**Review by Faustin250 — APPROVED** [review]

**Review by nkalyesubula — APPROVED** [review]
Please fix failing tests

**Comment by Remkuzo98** [comment]
> Please fix failing tests

fixed

**Pull request merged**
