### PR TITLE
Chore:Postgres Database and sequelize configuration

### PR DESCRIPTION
**Pull request by nishimweelysee**
#### Screenshots (if appropriate)
image

Thank you !!

### CODE REVIEW

**Comment by nishimweelysee** [comment]
[Configure the app to use Postgres database](https://trello.com/c/SDEbcUlY/17-configure-the-app-to-use-postgres-database)

**Review by bizip — CHANGES_REQUESTED** [review]
Guys, It good but one more thing I need you to work on is when I am trying to follow the instruction I am getting this error otherwise you have done a great job
Screen Shot 2020-10-15 at 11 58 14

**Review by bizip — APPROVED** [review]

**Review by muhireheir — CHANGES_REQUESTED** [review]
Congz to team 3! it would be better if you provide required database configuration setup in `README.MD`

**Review by mugisha1555 — APPROVED** [review]

**Review by sebastien15 — APPROVED** [review]
Good work! team 3 i reviewed everything and it is working on locally

**Review by nkalyesubula — CHANGES_REQUESTED** [review]
Good work so far. However address the following issues:-
1. Provide .env.example file  in your codebase and populate it with all the required variables
2. Correct your PR title. Use the task description as your PR title i.e"Configure the app to use Postgres database"
3. Use a meaningful branch name. "ch-config-postgres-db" would be a better name
4. Remove all the "_DEV" from the constants names i.e use DB_NAME instead of DB_NAME_DEV. 
5. Squash your commits into 1 commit.

**Comment by nishimweelysee** [comment]
> 
> 
> Good work so far. However address the following issues:-
> 
>     1. Provide .env.example file  in your codebase and populate it with all the required variables
> 
>     2. Correct your PR title. Use the task description as your PR title i.e"Configure the app to use Postgres database"
> 
>     3. Use a meaningful branch name. "ch-config-postgres-db" would be a better name
> 
>     4. Remove all the "_DEV" from the constants names i.e use DB_NAME instead of DB_NAME_DEV.
> 
>     5. Squash your commits into 1 commit.


on Fourth point :
will we use same database for testing,development and production? Because we have added that _DEV to differentiate it with test db where we have use _TEST and production where we have use _PROD

**Review by muhireheir — CHANGES_REQUESTED** [review]
wow! it's looking good  but rember to remove `DEV` suffix in `README file` also  as mentioned by noah

**Review by muhireheir — APPROVED** [review]
Approved

**Pull request closed without merging**
