### PR TITLE
Comment on Travel Request

### PR DESCRIPTION
**Pull request by nishimweelysee**
#### Any background context you want to provide?
ID Parameter is for the travel request you want to view to comment on.
#### Screenshots (if appropriate)

> commenting on request 
image
> viewing all comments
image

Thank you

### CODE REVIEW

**Comment by nishimweelysee** [comment]
[Comment on travel requests](https://trello.com/c/4HfhfMub/13-comment-on-travel-requests)

**Review by Faustin250 — APPROVED** [review]
The PR is working correctly

**Review by bizip — CHANGES_REQUESTED** [review]
Good looking, but something I need you to work on is to remove `console.log` in comments controller.js line 15

**Review by muhireheir — APPROVED** [review]
good work

**Comment by bizip** [comment]
> Good looking, but something I need you to work on is to remove `console.log` in comments controller.js line 15

Solved

**Review by bizip — APPROVED** [review]

**Review by Remkuzo98 — COMMENTED** [review]
this PR is working perfectly fine but try to resolve the conflicts

**Comment by nishimweelysee** [comment]
> this PR is working perfectly fine but try to resolve the conflicts

Yeah done

**Review by Remkuzo98 — APPROVED** [review]

**Pull request merged**
