### PR TITLE
ch(Setup project): initial folder structure for Barefoot Nomad

### PR DESCRIPTION
**Pull request by bizip**
#### What does this PR do?

- Created folder structure

- Created welcome endpoint

- Configured ESLint

- Created API documentation using swagger

#### Description of Task to be completed

- All task above is completed

#### How should this be manually tested?

1. Clone this repository into your computer

2. Switch to the ch-project-setup branch

3. Run `npm install` press enter

4.Run `npm run dev`  press enter

5. Open postman and type the links provided on the screenshot
image
 
#### What are the relevant Trello story?
https://trello.com/c/qgZZcypX
#### Screenshots (if appropriate)

1. Screenshot of welcome documented endpoint
image

2. Screenshot of welcome documented endpoint
image

[ Done ]

### CODE REVIEW

**Review by muhireheir — APPROVED** [review]

**Review by sebastien15 — APPROVED** [review]
well structured!

**Comment by nishimweelysee** [comment]
It's fine

**Comment by bizip** [comment]
[Set up Node.js REST API empty project.](https://trello.com/c/qgZZcypX/23-set-up-nodejs-rest-api-empty-project)

**Review by nishimweelysee — APPROVED** [review]
It's fine

**Pull request closed without merging**
