### PR TITLE
Setup Continuous Integration & Quality Assurance pipeline

### PR DESCRIPTION
**Pull request by muhireheir**
**What does this PR do?**

 - Configures Testing environment with Mocha, Chai and Sinon to ensure that all functionalities are tested before deployment.
- Travis CI is configured as a continuous integration service used to build and test the app.
- Configures Heroku Pipeline on Heroku
- Adds Travis CI and CodeClimate  badges  on this repo
- Configures CodeClimate for code analysis and Maintainability checking.

**Description of Task to be completed**
- All the necessary task for this PR are completed

 **How should this be manually tested?**

1 **Testing for continuous integration,code maintainability  and test coverage**

- switch to `ch-unitest-travisAndHeroku-configuration` branch and check if all badges are present
Screenshot

2 **Testing if app is hosted on Heroku**
- open this link [https://phoenix-bn-staging.herokuapp.com//](https://phoenix-bn-staging.herokuapp.com//)

**What is the relevant Trello story?**
- [https://trello.com/c/C3AgjVc1/](https://trello.com/c/C3AgjVc1)

### CODE REVIEW

**Review by nishimweelysee — APPROVED** [review]
I see you have worked on the feedback, the branch named it's fine.

**Review by sebastien15 — APPROVED** [review]
Well done!!!

**Comment by Faustin250** [comment]
You did a great job, continue that way

**Review by Faustin250 — APPROVED** [review]
You did a great job, continue that way!

**Review by nkalyesubula — APPROVED** [review]
LGTM

**Comment by muhireheir** [comment]
[Setup Continuous Integration & Quality Assurance pipeline](https://trello.com/c/C3AgjVc1/18-setup-continuous-integration-quality-assurance-pipeline)

**Pull request merged**
