### PR TITLE
Ch setup Travis Ci Code quality assurance with CodeClimate and heroku pipeline

### PR DESCRIPTION
**Pull request by muhireheir**
**What does this PR do?**

 - Configures Testing environment with Mocha, Chai and Sinon to ensure that all functionalities are tested before deployment.
- Travis CI is configured as a continuous integration service used to build and test the app.
- Configures Heroku Pipeline on Heroku
- Adds Travis CI and CodeClimate  badges  on this repo
- Configures CodeClimate for code analysis and Maintainability checking.

**Description of Task to be completed**
- All the necessary task for this PR are completed

 **How should this be manually tested?**

1 **Testing for continuous integration,code maintainability  and test coverage**

- switch to `ch-setupCi` branch and check if all badges are present
Screenshot

2 **Testing if app is hosted on Heroku**
- open this link [https://phoenix-bn.herokuapp.com/](https://phoenix-bn.herokuapp.com/)

**What is the relevant Trello story?**
- [https://trello.com/c/C3AgjVc1/](https://trello.com/c/C3AgjVc1)

### CODE REVIEW

**Comment by muhireheir** [comment]
[Setup Continuous Integration & Quality Assurance pipeline](https://trello.com/c/C3AgjVc1/18-setup-continuous-integration-quality-assurance-pipeline)

**Review by nishimweelysee — APPROVED** [review]
Now it's fine , you have did well on Noah's feedback.

**Review by bizip — APPROVED** [review]

**Review by mugisha1555 — APPROVED** [review]

**Review by Faustin250 — APPROVED** [review]
Looks good so far. You can merge

**Review by nkalyesubula — CHANGES_REQUESTED** [review]
Thanks for the efforts so far. However address the following issues:-
1. Correct the PR title based on the conventions we agreed upon
2. You have 10 commits, please squash them into 1 commit. (use the resource i shared with you on slack to achieve this).
3. Please use meaningful commit messages. How can "ok" possibly be a commit message?
4. Add a vivid description of the project in the README file
5. use a meaningful branch name

**Review by nishimweelysee — APPROVED** [review]
Yeah now it fine, you have worked on Readme file feedback but work on Branch naming, I think other content will be added later.

**Pull request closed without merging**
