### PR TITLE
Configure the app to use Postgres database

### PR DESCRIPTION
**Pull request by nishimweelysee**
#### Screenshots (if appropriate)
image

Thank you !!

### CODE REVIEW

**Review by sebastien15 — APPROVED** [review]
You made a good work Group 3

**Review by muhireheir — APPROVED** [review]
Approved!

**Review by Remkuzo98 — COMMENTED** [review]
this pr looks good
 great work so far

**Review by Remkuzo98 — COMMENTED** [review]
great work

**Review by nkalyesubula — APPROVED** [review]
LGTM

**Pull request merged**
