### PR TITLE
ch-project-setup: Initial folder structure and welcome endpoint for Barefoot Nomad 

### PR DESCRIPTION
**Pull request by mugisha1555**
**What does this PR do?**

 - Creates a welcome endpoint
- Creates the project structure
- Configures ESLint for code analysis and set up a script in package.json to lint files
- Creates API documentation with Swagger

**Description of Task to be completed**
- All the necessary task for this PR are finished

 **How should this be manually tested?**

1. Cloning this repository to your local machine. 

2. Switch to a branch named ch-project-setup

3. Open Terminal on your code editor and type `npm i` then type `npm run dev` to start the server

4. After the server has started and is listening, open the postman app and enter the address to the server as shown below in the screenshot 
postman1
 
**What is the relevant Trello story?**
- https://trello.com/c/qgZZcypX/23-set-up-nodejs-rest-api-empty-project

 **Screenshots (if appropriate)**
 Screenshots of a documented  welcome endpoint with swagger

95779585-9654d080-0cca-11eb-8318-af86879ff5c2

95780126-9f926d00-0ccb-11eb-92ce-7e2dcf25700c

### CODE REVIEW

**Review by nishimweelysee — APPROVED** [review]
Appreved

**Review by muhireheir — APPROVED** [review]
Approved

**Review by sebastien15 — APPROVED** [review]

**Review by nkalyesubula — CHANGES_REQUESTED** [review]
Looks good so far. I'd love you put swagger.json file in a folder called swagger, and Since we're working on a large project, lets get rid of .json files and have index.js that will be importing swagger endpoints from different files based on the module (e.g welcome.swagger.js, signin.swagger.js, signup.swagger.js etc). The current implementation ensures that all swagger endpoints are written in swagger.json file which is really overwhelming and difficult to manage

**Review by Remkuzo98 — APPROVED** [review]

**Review by nkalyesubula — CHANGES_REQUESTED** [review]
Kindly correct the controllers folder name from "contollers" to "controllers". Also fix eslint issues in welcome.swagger.js
 
Screenshot (253)

**Review by nkalyesubula — APPROVED** [review]

**Pull request merged**
